volumes:
  data:

services:
  security_app:
    container_name: security_app
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - ultimattern
    image: security_app:${IMAGE_VERSION}
    restart: no
    ports:
      - '8080:8080'
    depends_on:
      - security_db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://${postgres_domain}:${postgres_port}/${postgres_db}
      - SPRING_DATASOURCE_USERNAME=${postgres_username}
      - SPRING_DATASOURCE_PASSWORD=${postgres_password}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
  security_db:
    image: 'postgres:latest'
    container_name: security_db
    networks:
      - ultimattern
    restart: no
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=${postgres_username}
      - POSTGRES_PASSWORD=${postgres_password}
      - POSTGRES_DB=${postgres_db}
    volumes:
      - data:/var/lib/postgresql/data

networks:
  ultimattern:
    name: ultimattern